# Generated by Django 3.1.7 on 2021-04-04 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('sale_price', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Цена на продажу')),
                ('cost_price', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Себестоимость')),
                ('count', models.IntegerField(default=0, verbose_name='Товары в наличии')),
                ('count_sold', models.IntegerField(default=0, verbose_name='Проданные товары')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата продажи')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
            ],
        ),
    ]
