# Generated by Django 3.1.7 on 2021-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210404_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_date',
            field=models.DateTimeField(verbose_name='Дата продажи'),
        ),
    ]
