# Generated by Django 3.1.7 on 2021-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210404_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, max_digits=20, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=1, max_digits=20, verbose_name='Цена на продажу'),
        ),
    ]
