# Generated by Django 3.1.7 on 2021-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210404_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sum',
            field=models.IntegerField(default=0, editable=False, verbose_name='Остаток товаров'),
        ),
    ]
