# Generated by Django 3.1.7 on 2021-04-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210404_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(verbose_name='Дата добавления'),
        ),
    ]
