# Generated by Django 3.1.7 on 2021-04-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210404_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_date',
        ),
    ]
