# Generated by Django 3.1.7 on 2021-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210404_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Купленные товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_sold',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Проданные товары'),
        ),
    ]
