# Generated by Django 3.1.7 on 2021-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210407_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Купленные товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='Проданные товары'),
        ),
    ]
