# Generated by Django 3.1.7 on 2021-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210407_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='earns',
            field=models.IntegerField(default=0, editable=False, verbose_name='Выручка'),
        ),
    ]
