# Generated by Django 3.1.7 on 2021-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_earns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='Цена на продажу'),
        ),
    ]
