# Generated by Django 3.1.7 on 2021-04-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210411_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_earns',
        ),
    ]
