# Generated by Django 3.1.7 on 2021-04-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210416_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='available_count',
        ),
    ]
