# Generated by Django 3.2 on 2021-04-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
