# Generated by Django 3.1.7 on 2021-04-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210416_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
