# Generated by Django 3.1.7 on 2021-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, upload_to='feedbacks/%Y/%m', verbose_name='Изображение')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('message', models.TextField(verbose_name='Подробнее')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
            ],
        ),
    ]
